Added Job Stage querying to greenhouse gem
Grayscale-Labs/greenhouse_io pull request #20
Opened 2022-06-02 15:09 UTC by Sleachga

Add methods for querying ALL job stages

2022-06-03 04:29 UTC, etipton requested changes
naming convention changes

2022-06-03 04:29 UTC, etipton commented on lib/greenhouse_io/api/client.rb
> +require 'greenhouse_io/api/job_stages_collection'
can you switch this to `job_stage_collection` to be consistent w/ other naming conventions in this repo?

2022-06-03 04:29 UTC, etipton commented on lib/greenhouse_io/api/job_stages.rb
> +  class JobStages < Resource
`JobStage`

2022-06-06 15:04 UTC, Sleachga commented on lib/greenhouse_io/api/client.rb
> +require 'greenhouse_io/api/job_stages_collection'
Fixed in 22c0e83f3a843bc2788acfaf16a8d70013e337e0

2022-06-07 14:27 UTC, merged