"dry" up hydrated resources by default
Grayscale-Labs/greenhouse_io pull request #28
Opened 2022-11-21 22:24 UTC by jakswa

- taking another path to solve https://app.shortcut.com/grayscale/story/8428/apply-memory-savings-changes-to-greenhouse-client-gem

This ended up much quicker than the alternative "just keep a single page around" I implemented elsewhere. In the gem we have two `include Enumerable` classes meshed together here that are both hydrating arrays.

This will break any enum usage that expects actual records in hydrated arrays. It pretty much only keeps `.count` (with _no arguments_) accurate. At least I would be very surprised if I couldn't run normal methods in a `.count { |record| record.method }` situation.

2022-11-21 22:25 UTC, jakswa commented on spec/greenhouse_io/api/candidate_collection_spec.rb
> +  end
I tried to demonstrate/document the surprising behavior in a couple specs.

2022-11-21 22:27 UTC, jakswa commented on lib/greenhouse_io/api/resource_collection.rb
>      def each_page
do we use `each_page` anywhere in our code? Depending on the usage, we might be keeping records around. Currently the cleanup on pages is only happening when the page is iterated through (`Page#each`).

2022-11-23 02:37 UTC, etipton commented on lib/greenhouse_io/api/resource_collection.rb
>      def each_page
Looks like we do, introduced in: https://github.com/Grayscale-Labs/cATs/pull/289

2022-11-23 02:50 UTC, etipton requested changes
couple thoughts, most significant is the response RE: `each_page`

2022-11-23 02:50 UTC, etipton commented on lib/greenhouse_io/api/resource_collection.rb
> +    # @param dry [Boolean] When true, we try to keep only `:dried` around in the hydration arrays
Love the idea of using `:dried` instead of `nil` (even better would be a "dummy class", e.g. `LazyPaginator::DryResource`)

WDYT of being more explicit w/ this param name, e.g. `dehydrate_after_iteration` or something?

2022-11-23 02:50 UTC, etipton commented on lib/greenhouse_io/api/resource_collection.rb
> +      @dry = dry
Any opposition to using attr_accessor like w/ the other params? FWIW, I used to think it felt too "formal" to do that, but then I read a blog post similar to [this one](https://ivoanjo.me/blog/2017/09/20/why-i-always-use-attr_reader-to-access-instance-variables/) which convinced me to pretty much avoid ivars (aside from memoization) -- overall though, DWYTIB, this is just a "nit" comment

2022-12-06 15:14 UTC, jakswa commented
The latest commit renames the variable and adopts the `attr_accessor` in classes using that. I spent some time trying clean up pages, but that code got hard to follow and I stared at our `each_page` usage and verified we are calling `Page#each`.

2022-12-06 17:47 UTC, kphan32 approved these changes
lgtm :+1:

2022-12-13 18:17 UTC, merged